<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;
use Carbon\Carbon;

class CoursesTableSeeder extends Seeder
{
    public function run()
    {
        $courses = [
            // Web Development Courses
            [
                'category_id' => 1,
                'subcategory_id' => 1,
                'instructor_id' => 1,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Frontend Development',
                'course_name' => 'Learn the Basics of HTML, CSS, and JavaScript',
                'course_name_slug' => 'learn-the-basics-of-html-css-and-javascript',
                'description' => 'Learn how to create beautiful websites with HTML, CSS, and JavaScript.',
                'video' => 'https://www.example.com/video1',
                'label' => 'Beginner Friendly',
                'duration' => '10 hours',
                'resources' => 'ebooks, exercises',
                'certificate' => true,
                'selling_price' => 99.99,
                'discount_price' => 49.99,
                'prerequisites' => 'Basic computer knowledge',
                'bestseller' => true,
                'featured' => true,
                'highestrated' => true,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 1,
                'subcategory_id' => 2,
                'instructor_id' => 2,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Backend Development with Node.js',
                'course_name' => 'Building Powerful Backend Systems',
                'course_name_slug' => 'building-powerful-backend-systems',
                'description' => 'Master backend development with Node.js for building scalable applications.',
                'video' => 'https://www.example.com/video2',
                'label' => 'Intermediate Level',
                'duration' => '15 hours',
                'resources' => 'ebooks, code examples',
                'certificate' => true,
                'selling_price' => 129.99,
                'discount_price' => 79.99,
                'prerequisites' => 'Basic programming knowledge',
                'bestseller' => true,
                'featured' => true,
                'highestrated' => false,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Full Stack Development
            [
                'category_id' => 1,
                'subcategory_id' => 3,
                'instructor_id' => 1,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Full Stack Development',
                'course_name' => 'Mastering Frontend and Backend',
                'course_name_slug' => 'mastering-frontend-and-backend',
                'description' => 'Become a full-stack developer with knowledge of both frontend and backend.',
                'video' => 'https://www.example.com/video3',
                'label' => 'Advanced Level',
                'duration' => '30 hours',
                'resources' => 'tutorials, projects',
                'certificate' => true,
                'selling_price' => 199.99,
                'discount_price' => 149.99,
                'prerequisites' => 'Frontend and backend experience',
                'bestseller' => true,
                'featured' => true,
                'highestrated' => true,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Data Science Courses
            [
                'category_id' => 2,
                'subcategory_id' => 3,
                'instructor_id' => 4,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Intro to Python Programming',
                'course_name' => 'Start with Python',
                'course_name_slug' => 'start-with-python',
                'description' => 'An introduction to Python for data science.',
                'video' => 'https://www.example.com/video4',
                'label' => 'Beginner Friendly',
                'duration' => '8 hours',
                'resources' => 'Python exercises, notebooks',
                'certificate' => true,
                'selling_price' => 79.99,
                'discount_price' => 39.99,
                'prerequisites' => 'No prior programming knowledge required',
                'bestseller' => false,
                'featured' => true,
                'highestrated' => false,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'subcategory_id' => 4,
                'instructor_id' => 5,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Machine Learning Essentials',
                'course_name' => 'Foundations of Machine Learning',
                'course_name_slug' => 'foundations-of-machine-learning',
                'description' => 'Learn the foundations of machine learning with hands-on projects.',
                'video' => 'https://www.example.com/video5',
                'label' => 'Intermediate Level',
                'duration' => '20 hours',
                'resources' => 'ML projects, datasets',
                'certificate' => true,
                'selling_price' => 149.99,
                'discount_price' => 99.99,
                'prerequisites' => 'Basic programming knowledge',
                'bestseller' => true,
                'featured' => true,
                'highestrated' => true,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'subcategory_id' => 6,
                'instructor_id' => 6,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Big Data Analytics',
                'course_name' => 'Processing and Analyzing Large Datasets',
                'course_name_slug' => 'processing-and-analyzing-large-datasets',
                'description' => 'Dive into big data analysis and processing with industry tools.',
                'video' => 'https://www.example.com/video6',
                'label' => 'Advanced Level',
                'duration' => '25 hours',
                'resources' => 'big data projects, code samples',
                'certificate' => true,
                'selling_price' => 199.99,
                'discount_price' => 149.99,
                'prerequisites' => 'Data Science basics, Python knowledge',
                'bestseller' => true,
                'featured' => false,
                'highestrated' => true,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 2,
                'subcategory_id' => 7,
                'instructor_id' => 7,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Data Visualization',
                'course_name' => 'Turning Data into Insights',
                'course_name_slug' => 'turning-data-into-insights',
                'description' => 'Master data visualization using tools like Tableau and Power BI.',
                'video' => 'https://www.example.com/video7',
                'label' => 'Intermediate Level',
                'duration' => '18 hours',
                'resources' => 'Visualization tools, datasets',
                'certificate' => true,
                'selling_price' => 129.99,
                'discount_price' => 99.99,
                'prerequisites' => 'Basic Data Science knowledge',
                'bestseller' => false,
                'featured' => true,
                'highestrated' => true,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Design Courses
            [
                'category_id' => 3,
                'subcategory_id' => 8,
                'instructor_id' => 8,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => 'Graphic Design Basics',
                'course_name' => 'Creating Stunning Visuals',
                'course_name_slug' => 'creating-stunning-visuals',
                'description' => 'A beginner\'s guide to graphic design with real-world projects.',
                'video' => 'https://www.example.com/video8',
                'label' => 'Beginner Friendly',
                'duration' => '12 hours',
                'resources' => 'Design tutorials, templates',
                'certificate' => true,
                'selling_price' => 79.99,
                'discount_price' => 49.99,
                'prerequisites' => 'No prior experience required',
                'bestseller' => false,
                'featured' => false,
                'highestrated' => true,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => 3,
                'subcategory_id' => 9,
                'instructor_id' => 9,
                'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
                'course_title' => '3D Design and Animation',
                'course_name' => 'Modeling and Rendering',
                'course_name_slug' => 'modeling-and-rendering',
                'description' => 'Learn how to create 3D models and render them with powerful tools.',
                'video' => 'https://www.example.com/video9',
                'label' => 'Advanced Level',
                'duration' => '20 hours',
                'resources' => '3D modeling tools, software',
                'certificate' => true,
                'selling_price' => 199.99,
                'discount_price' => 149.99,
                'prerequisites' => 'Experience with design software',
                'bestseller' => true,
                'featured' => false,
                'highestrated' => false,
                'status' => 1, // Active
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Business Courses
[
    'category_id' => 4,
    'subcategory_id' => 11,
    'instructor_id' => 11,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Entrepreneurship 101',
    'course_name' => 'Starting Your Own Business',
    'course_name_slug' => 'starting-your-own-business',
    'description' => 'Learn the basics of entrepreneurship and how to start your own successful business.',
    'video' => 'https://www.example.com/video10',
    'label' => 'Beginner Friendly',
    'duration' => '12 hours',
    'resources' => 'Business templates, case studies',
    'certificate' => true,
    'selling_price' => 99.99,
    'discount_price' => 59.99,
    'prerequisites' => 'None',
    'bestseller' => false,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 4,
    'subcategory_id' => 12,
    'instructor_id' => 12,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Leadership Skills',
    'course_name' => 'Managing Teams Effectively',
    'course_name_slug' => 'managing-teams-effectively',
    'description' => 'Develop leadership skills that will help you manage teams and lead them to success.',
    'video' => 'https://www.example.com/video11',
    'label' => 'Intermediate Level',
    'duration' => '15 hours',
    'resources' => 'Leadership frameworks, worksheets',
    'certificate' => true,
    'selling_price' => 129.99,
    'discount_price' => 89.99,
    'prerequisites' => 'Experience managing teams',
    'bestseller' => true,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 4,
    'subcategory_id' => 13,
    'instructor_id' => 13,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Project Management Essentials',
    'course_name' => 'Planning and Executing Projects',
    'course_name_slug' => 'planning-and-executing-projects',
    'description' => 'Learn how to manage projects from start to finish, including planning and execution.',
    'video' => 'https://www.example.com/video12',
    'label' => 'Intermediate Level',
    'duration' => '18 hours',
    'resources' => 'Project management tools, templates',
    'certificate' => true,
    'selling_price' => 149.99,
    'discount_price' => 99.99,
    'prerequisites' => 'None',
    'bestseller' => false,
    'featured' => false,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 4,
    'subcategory_id' => 14,
    'instructor_id' => 14,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Business Strategy',
    'course_name' => 'Analyzing and Planning for Success',
    'course_name_slug' => 'analyzing-and-planning-for-success',
    'description' => 'Learn how to develop business strategies that drive growth and success.',
    'video' => 'https://www.example.com/video13',
    'label' => 'Advanced Level',
    'duration' => '20 hours',
    'resources' => 'Strategy frameworks, case studies',
    'certificate' => true,
    'selling_price' => 179.99,
    'discount_price' => 129.99,
    'prerequisites' => 'Business knowledge',
    'bestseller' => true,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],

// Marketing Courses
[
    'category_id' => 5,
    'subcategory_id' => 15,
    'instructor_id' => 15,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Digital Marketing Fundamentals',
    'course_name' => 'Reaching Audiences Online',
    'course_name_slug' => 'reaching-audiences-online',
    'description' => 'Master the basics of digital marketing including SEO, PPC, and social media strategies.',
    'video' => 'https://www.example.com/video14',
    'label' => 'Beginner Friendly',
    'duration' => '10 hours',
    'resources' => 'Digital marketing tools, templates',
    'certificate' => true,
    'selling_price' => 99.99,
    'discount_price' => 69.99,
    'prerequisites' => 'None',
    'bestseller' => true,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 5,
    'subcategory_id' => 16,
    'instructor_id' => 16,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Content Marketing Strategies',
    'course_name' => 'Creating Engaging Content',
    'course_name_slug' => 'creating-engaging-content',
    'description' => 'Learn how to create compelling content that drives engagement and conversions.',
    'video' => 'https://www.example.com/video15',
    'label' => 'Intermediate Level',
    'duration' => '15 hours',
    'resources' => 'Content calendars, case studies',
    'certificate' => true,
    'selling_price' => 119.99,
    'discount_price' => 79.99,
    'prerequisites' => 'Basic content creation knowledge',
    'bestseller' => false,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 5,
    'subcategory_id' => 17,
    'instructor_id' => 17,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'SEO Optimization',
    'course_name' => 'Improving Website Visibility',
    'course_name_slug' => 'improving-website-visibility',
    'description' => 'Learn how to optimize websites for search engines and improve ranking.',
    'video' => 'https://www.example.com/video16',
    'label' => 'Intermediate Level',
    'duration' => '18 hours',
    'resources' => 'SEO tools, case studies',
    'certificate' => true,
    'selling_price' => 149.99,
    'discount_price' => 99.99,
    'prerequisites' => 'Basic knowledge of digital marketing',
    'bestseller' => true,
    'featured' => true,
    'highestrated' => false,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 5,
    'subcategory_id' => 18,
    'instructor_id' => 18,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Social Media Marketing',
    'course_name' => 'Building Brand Awareness',
    'course_name_slug' => 'building-brand-awareness',
    'description' => 'Learn how to leverage social media platforms for effective marketing campaigns.',
    'video' => 'https://www.example.com/video17',
    'label' => 'Beginner Friendly',
    'duration' => '12 hours',
    'resources' => 'Social media strategies, case studies',
    'certificate' => true,
    'selling_price' => 109.99,
    'discount_price' => 79.99,
    'prerequisites' => 'None',
    'bestseller' => true,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 5,
    'subcategory_id' => 15,
    'instructor_id' => 19,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Advanced Social Media Marketing',
    'course_name' => 'Building Your Brand',
    'course_name_slug' => 'building-your-brand',
    'description' => 'Take your social media skills to the next level and build a strong brand presence.',
    'video' => 'https://www.example.com/video18',
    'label' => 'Advanced Level',
    'duration' => '25 hours',
    'resources' => 'Social media guides, campaigns',
    'certificate' => true,
    'selling_price' => 179.99,
    'discount_price' => 129.99,
    'prerequisites' => 'Basic social media knowledge',
    'bestseller' => true,
    'featured' => false,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 5,
    'subcategory_id' => 16,
    'instructor_id' => 20,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Search Engine Marketing',
    'course_name' => 'Mastering PPC and Ads',
    'course_name_slug' => 'mastering-ppc-and-ads',
    'description' => 'Learn how to create successful PPC campaigns to maximize conversions.',
    'video' => 'https://www.example.com/video19',
    'label' => 'Intermediate Level',
    'duration' => '15 hours',
    'resources' => 'PPC tools, case studies',
    'certificate' => true,
    'selling_price' => 149.99,
    'discount_price' => 99.99,
    'prerequisites' => 'Basic digital marketing knowledge',
    'bestseller' => false,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
[
    'category_id' => 5,
    'subcategory_id' => 17,
    'instructor_id' => 21,
    'course_image' => 'http://127.0.0.1:8000/upload/no_image.jpg',
    'course_title' => 'Advanced SEO',
    'course_name' => 'Boost Your Website Rankings',
    'course_name_slug' => 'boost-your-website-rankings',
    'description' => 'Learn advanced SEO techniques for boosting website rankings and driving organic traffic.',
    'video' => 'https://www.example.com/video20',
    'label' => 'Advanced Level',
    'duration' => '30 hours',
    'resources' => 'Advanced SEO tools, case studies',
    'certificate' => true,
    'selling_price' => 199.99,
    'discount_price' => 149.99,
    'prerequisites' => 'Basic SEO knowledge',
    'bestseller' => true,
    'featured' => true,
    'highestrated' => true,
    'status' => 1, // Active
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
],
        ];

        foreach ($courses as $course) {
            Course::firstOrCreate(
                ['course_title' => $course['course_title']],
                $course
            );
        }
    }
}
